import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import type { ReactNode } from "react";
import NavBar from "@/components/navBar"
import Footer from "@/components/footer"
import Social from "@/components/custom/social"
import {getUserMeLoader} from "@/data/services/get-user-me-loader"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Noncense",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const user = await getUserMeLoader();
  // console.log('----------->user data layout=>', user)
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar user={user}/>
          <div className="mt-16">
          {children}
          </div>
          <Footer/>
          <Social/>
        </ThemeProvider>
      </body>
    </html>
  );
}
